
#default: &default
#  adapter: postgresql
#  pool: 5
#  timeout: 5000
#
#development:
#  <<: *default
#  database: db/development

#test:
#  <<: *default
#  database: db/test

#production:
#  <<: *default
#  database: db/production



development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: 
  password: